# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ElbowLD_joint:
    has_velocity_limits: true
    max_velocity: 4.1887999999999996
    has_acceleration_limits: true
    max_acceleration: 5.0
  ElbowLU_joint:
    has_velocity_limits: true
    max_velocity: 19.896999999999998
    has_acceleration_limits: true
    max_acceleration: 10.0
  ElbowRD_joint:
    has_velocity_limits: true
    max_velocity: 4.1887999999999996
    has_acceleration_limits: true
    max_acceleration: 5.0
  ElbowRU_joint:
    has_velocity_limits: true
    max_velocity: 19.896999999999998
    has_acceleration_limits: true
    max_acceleration: 10.0
  ShoulderLD_joint:
    has_velocity_limits: true
    max_velocity: 4.1887999999999996
    has_acceleration_limits: true
    max_acceleration: 5.0
  ShoulderLU_joint:
    has_velocity_limits: true
    max_velocity: 5.2359879999999999
    has_acceleration_limits: true
    max_acceleration: 6.0
  ShoulderRD_joint:
    has_velocity_limits: true
    max_velocity: 4.1887999999999996
    has_acceleration_limits: true
    max_acceleration: 5.0
  ShoulderRU_joint:
    has_velocity_limits: true
    max_velocity: 5.2359879999999999
    has_acceleration_limits: true
    max_acceleration: 6.0
  WristLD_joint:
    has_velocity_limits: true
    max_velocity: 32.463124000000001
    has_acceleration_limits: true
    max_acceleration: 15.0
  WristLU_joint:
    has_velocity_limits: true
    max_velocity: 19.897
    has_acceleration_limits: true
    max_acceleration: 10.0
  WristRD_joint:
    has_velocity_limits: true
    max_velocity: 32.463000000000001
    has_acceleration_limits: true
    max_acceleration: 15.0
  WristRU_joint:
    has_velocity_limits: true
    max_velocity: 19.897
    has_acceleration_limits: true
    max_acceleration: 10.0