move_group:
  ros__parameters:
    trajectory_execution:
      allowed_start_tolerance: 0.2
      allowed_goal_duration_margin: 5.0
      allowed_goal_tolerance: 0.05
      execution_duration_monitoring: false
